export const seedProducts = [
  {
    id: "miss-sensacao",
    name: "Miss Sensação",
    category: "Mousses",
    flavor: "Morango + chocolate",
    description:
      "Mousse de morango com chocolate. Uma dupla que acerta em cheio.",
    priceCents: 1000,
    image: "/images/miss-sensacao.webp",
    accent: "#f6b3ab",
    tag: "Queridinho",
    active: true,
    trackStock: false,
    stock: 0,
    lowStockThreshold: 5,
  },
  {
    id: "lil-palha",
    name: "Lil Palha",
    category: "Palhas",
    flavor: "Chocolate",
    description:
      "Palha italiana de chocolate, cremosa e com aquela mordida marcante.",
    priceCents: 700,
    image: "/images/lil-palha.webp",
    accent: "#d9ad81",
    tag: "",
    active: true,
    trackStock: false,
    stock: 0,
    lowStockThreshold: 5,
  },
  {
    id: "maradon",
    name: "MARADON",
    category: "Mousses",
    flavor: "Maracujá + chocolate",
    description:
      "Mousse de maracujá com chocolate. O azedinho encontra o intenso.",
    priceCents: 1000,
    image: "/images/maradon.webp",
    accent: "#f4d480",
    tag: "Contraste perfeito",
    active: true,
    trackStock: false,
    stock: 0,
    lowStockThreshold: 5,
  },
  {
    id: "mano-brownie",
    name: "MANO BROWNIE",
    category: "Brownie",
    flavor: "Chocolate",
    description:
      "Brownie de chocolate com sabor intenso e textura irresistível.",
    priceCents: 600,
    image: "/images/mano-brownie.webp",
    accent: "#bd8d73",
    tag: "",
    active: true,
    trackStock: false,
    stock: 0,
    lowStockThreshold: 5,
  },
  {
    id: "ninho-abravanel",
    name: "Ninho Abravanel",
    category: "Palhas",
    flavor: "Leite ninho",
    description: "Palha italiana de leite ninho para quem ama um doce cremoso.",
    priceCents: 700,
    image: "/images/ninho-abravanel.webp",
    accent: "#f0dfbd",
    tag: "",
    active: true,
    trackStock: false,
    stock: 0,
    lowStockThreshold: 5,
  },
];

export const seedSettings = {
  storeName: "Street Doces",
  tagline: "Doces que restauram sua essência.",
  instagramUrl: "https://www.instagram.com/street_doces/",
  whatsapp: "",
  pixKey: "matheusaagd2@gmail.com",
  pickupAddress: "Rua Estocolmo, 136 — Duque de Caxias, Betim/MG",
  announcement: "FEITO À MÃO EM BETIM, MG",
  acceptsOrders: true,
  pickupEnabled: true,
  deliveryEnabled: true,
  deliveryNotice:
    "A loja confirma disponibilidade, parceiro (99 ou Uber) e valor da entrega no atendimento.",
};
